services:
  apitest:
    build:
      context: ./api
      target: development
    volumes:
      - ./api:/api
      - ./api/node_modules:/api/node_modules
    env_file:
      - ./.env.test
    command: pnpm run test:e2e --watchAll
    depends_on:
      - dbtest
    networks:
      - test_network
    ports:
      - "3000:3000"

  dbtest:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - db_data_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: $POSTGRES_DB
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    command: -p 5433
    env_file:
      - ./.env.test
    networks:
      - test_network

volumes:
  db_data_test:

networks:
  test_network:
    driver: bridge
