services:
  api:
    build:
      context: ./api
      target: development
    volumes:
      - ./api:/api
      - ./api/node_modules:/api/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    command: pnpm run start:dev
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
