# Use the latest Alpine Python image
FROM --platform=linux/amd64 python:3.12-alpine

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

RUN apk update
RUN apk add git

# Install the required packages
RUN pip install -r requirements.txt
RUN pip install git+https://github.com/huggingface/diffusers

# Copy the Flask app code
COPY . .

ENV FLASK_APP=app.py
# Expose the port on which the Flask app will run
EXPOSE 8000

# Set the entrypoint command to run the Flask app
CMD ["python", "app.py" ,"--host=0.0.0.0"]
