# Use the latest Alpine Python image
FROM python:alpine

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

RUN apk update
RUN apk add git

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install accelerate
RUN pip install git+https://github.com/huggingface/diffusers
RUN pip3 install torch torchvision

# Copy the Flask app code
COPY . .

ENV FLASK_APP=app.py
# Expose the port on which the Flask app will run
EXPOSE 5000

# Set the entrypoint command to run the Flask app
CMD ["python", "app.py" ,"--host=0.0.0.0"]
