apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-depl
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: chat-config
          # volumeMounts:
          #   - mountPath: /data
          #     name: redis-storage
          # args:
          #   - "--save"
          #   - ""
          #   - "--appendonly"
          #   - "no"

      # volumes:
      #   - name: redis-storage
      #     persistentVolumeClaim:
      #       claimName: pv-claim-redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis-srv
  namespace: chat-app
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: db-connection
